name: Test on Multiple OS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] # Operating systems to test
        node-version: [18, 20, 22]                      # Node.js versions to test
        attempt: [1, 2, 3, 4, 5]                        # Repeat tests 5 times

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Ensure Python 3 is installed (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python-is-python3

      - name: Set Python path for node-gyp (Linux & macOS)
        if: runner.os != 'Windows'
        run: |
          echo "Using Python: $(which python3)"
          export PYTHON=$(which python3)

      - name: Set Python path for node-gyp (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "Using Python: $(where python)"
          setx PYTHON "C:\\Path\\To\\Python3\\python.exe"

      - name: Upgrade node-gyp
        run: npm install -g node-gyp

      - name: Clean and install dependencies
        run: |
          if ($env:RUNNER_OS -eq "Windows") {
            Remove-Item -Recurse -Force node_modules, package-lock.json
          } else {
            rm -rf node_modules package-lock.json
          }
          npm cache clean --force
          npm install --force

      - name: Testing on OS (${{ matrix.os }}) with Node.js (version ${{ matrix.node-version }}) attempt ${{ matrix.attempt }}
        run: |
          echo "Run attempt: ${{ matrix.attempt }}"
          npm test

    continue-on-error: false
